### ISSUE TITLE
[Pre-release Plus 1 4 0]

### ISSUE THREAD

**Issue by RandomGOTI** [sandboxie-plus/Sandboxie#2301]
### Describe what you noticed and did

- [x] Box 2x click action customization , `DblClickAction=!options` is not necesarry to be in the ini since it's default behaviour
     -Once this feature is used , and wish to return to default , this extra line cannot be removed unless ini edited manually
- [x] 2xclicking on a template in app templates tab to edit it will not switch to edit ini tab automatically
- [x] while editing a template some tabs can be clicked
![options tabs](https://user-images.githubusercontent.com/19516333/193917475-3b5db306-66ab-4f66-a511-1e22d3819928.png)

- [ ] ...
- A 'Miscellaneous setting that is added to a template in globalsettings section cannot be overruled by a settings added directly to the box example `BoxNameTitle=app.exe,-` in global template and `BoxNameTitle=app.exe,n` in box section ; The one in box section (`BoxNameTitle=app.exe,n`) won't work but if i add it to a local(sanbox) template it will. 
 _(Box also has `BoxNameTitle=y` ; default is `n`)_
- Now with a toggle option like `UseRuleSpecificity` if added to a global template `UseRuleSpecificity=y` and then have a local template `UseRuleSpecificity=n` seems like it does not work , but works if added directly to the box or if added directly to globalsettings then a local template will work. In previous version (Plus 1.3.5) a local template will overrule even a global enabled template since the messages have started after updating to v1.4.0  #1955 
- Setting should take priority based on how direct they are : Global Template < Global Settings < Sandbox Template < Sandbox
- [ ] BoxBorder / Box Icons #2184 Not handling hexcolor codes corectly
- [ ] #2111 💀 cannot be reopened
- [ ] #1825 This issue is back when using Esc key instead of pressing cancel to close box options

### Affected program

.

### Download link

.

### Where is the program located?

Not relevant to my request.

### Expected behavior

.

### What is your Windows edition and version?

Windows 7 Ultimate SP1 x64

### In which Windows account you have this problem?

I use the built-in Administrator account.

### Please mention any installed security software

None/WD disabled

### What version of Sandboxie are you running?

Plus 1 4 0 x64

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (to be specified).

### In which sandbox type you have this problem?

Not relevant to my request.

### Can you reproduce this problem on an empty sandbox?

Not relevant to my request.

**Comment by DavidXanatos** [comment]
cant reproduce: https://github.com/sandboxie-plus/Sandboxie/issues/1825

**Comment by RandomGOTI** [comment]
@DavidXanatos 

> can't reproduce: #1825 isn't #2111 expected behavioure in the end we want to see how a box will act when used be that local or global config is not relevant #2184 is the legacy order in which sandboxie classic parses the hex code and it will stay this way

1825 Create a new box or have a new config generated by sandboxie
Issue related to the absence of `ClosedFilePath=<BlockNetDevices>,InternetAccessDevices` in ini but can see it resorce access  while cruising trough the tabs
Dialog does not show if Cancel button is used instead of Esc key

https://user-images.githubusercontent.com/19516333/194678028-f9668909-10c1-47b1-a6bd-8624acc1f5f2.mp4

2111 I missunderstood the label and 1.3.1 changelog `fixed issue with displaying sandbox configuration` or you've changed your mind on having the feature in 1 3 x and future builds , I am fine with both cases

2184 Can confirm the issue goes that far back with 5.40 x64, closing that issue
